name: 掘金自动签到、抽奖及挖矿
on:
  push:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 01表示北京时间上午9点
    - cron: '0 01 * * *'
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: use branch=>master
        uses: actions/checkout@master

      - name: 使用 node:16.3.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0

      - name: npm install
        run: |
          npm install

      - name: 运行脚本
        run: |
          npm start
