name: 掘金自动签到、抽奖及挖矿
on:
  push:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    - cron: '0 05 * * *'
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive

      - name: 使用 node:16.3.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0

      - name: npm install
        run: |
          npm install
        env:
          CI: true

      - name: 运行脚本
        run: |
          COOKIE='${{ secrets.COOKIE }}' TOKEN='${{ secrets.TOKEN }}' SendKey='${{ secrets.SendKey }}' npm start
        env:
          CI: true